module.exports = {
  FAKE: "FAKE",
  DEMO: "DEMO",
  PARTNER_COMPLAINT: "PARTNER_COMPLAINT",
  PARTNER_LEAD: "PARTNER_LEAD",
  GET_SERVICES: "GET_SERVICES",
  PARTNER_LIST_BY_CITY: "PARTNER_LIST_BY_CITY",
  PARTNER_DETAILS: "PARTNER_DETAILS",
  GET_USER_PARTNER_DETAILS: "GET_USER_PARTNER_DETAILS",
  PARTNER_RECORD: "PARTNER_RECORD",
  PARTNER_COMMENT: "PARTNER_COMMENT",
  USER_COMPLAINT: "USER_COMPLAINT",
  GET_STATE_CITY: "GET_STATE_CITY",
};
